version: '3.9'
services:
  db:
    image: mysql:5.7.16
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 1 
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/project_management
    ports:
      - "3000:3000"
    depends_on:
      - db
